import type { EnemyDef } from './types';

export const ENEMY_DEFS: Record<string, EnemyDef> = {
  rat: {
    id: 'rat',
    name: 'Rat',
    maxHp: 30,
    speed: 4,
    reward: 10,
    color: '#8b7355',
    traits: [],
    armor: 0,
    shield: 0,
  },
  pigeon: {
    id: 'pigeon',
    name: 'Pigeon',
    maxHp: 60,
    speed: 4.5,
    reward: 20,
    color: '#9ca3af',
    flying: true,
    traits: ['flying'],
    armor: 0,
    shield: 0,
  },
  dog: {
    id: 'dog',
    name: 'Dog',
    maxHp: 150,
    speed: 2.5,
    reward: 40,
    color: '#92400e',
    traits: [],
    armor: 0,
    shield: 0,
  },
  seagull: {
    id: 'seagull',
    name: 'Seagull',
    maxHp: 55,
    speed: 5.2,
    reward: 22,
    color: '#f1eee2',
    flying: true,
    traits: ['flying', 'shielded'],
    armor: 0,
    shield: 18,
  },
  boar: {
    id: 'boar',
    name: 'Boar',
    maxHp: 260,
    speed: 2.2,
    reward: 55,
    color: '#4a2b1d',
    traits: ['armored'],
    armor: 4,
    shield: 0,
  },
  fox: {
    id: 'fox',
    name: 'Fox',
    maxHp: 110,
    speed: 4.8,
    reward: 35,
    color: '#c9652e',
    traits: ['packLeader'],
    armor: 0,
    shield: 0,
    auraRadius: 6,
    auraSpeedMultiplier: 1.2,
  },
  emberWisp: {
    id: 'emberWisp',
    name: 'Ember Wisp',
    maxHp: 85,
    speed: 5.4,
    reward: 30,
    color: '#ff9d5c',
    flying: true,
    traits: ['flying', 'corrupted'],
    armor: 0,
    shield: 8,
  },
  cinderHound: {
    id: 'cinderHound',
    name: 'Cinder Hound',
    maxHp: 180,
    speed: 3.3,
    reward: 48,
    color: '#c5562e',
    traits: ['corrupted'],
    armor: 1,
    shield: 0,
  },
  tunnelDrone: {
    id: 'tunnelDrone',
    name: 'Tunnel Drone',
    maxHp: 210,
    speed: 3.6,
    reward: 52,
    color: '#8db5c8',
    traits: ['shielded'],
    armor: 2,
    shield: 20,
  },
  dragonMarked: {
    id: 'dragonMarked',
    name: 'Dragon-Marked',
    maxHp: 320,
    speed: 3.1,
    reward: 70,
    color: '#ffd27f',
    traits: ['armored', 'corrupted'],
    armor: 5,
    shield: 10,
  },
};
