import type { TowerDef } from './types';

export const TOWER_DEFS: Record<string, TowerDef> = {
  scratchingPost: {
    id: 'scratchingPost',
    name: 'Scratching Post',
    cost: 50,
    range: 8,
    damage: 10,
    fireRate: 2,
    projectileSpeed: 30,
    color: '#c4873b',
    role: 'Fast attack',
    statLine: 'Balanced DPS',
    effects: [],
    canTargetGround: true,
    canTargetFlying: false,
  },
  yarnLauncher: {
    id: 'yarnLauncher',
    name: 'Yarn Launcher',
    cost: 75,
    range: 12,
    damage: 5,
    fireRate: 1,
    projectileSpeed: 20,
    color: '#e85d75',
    special: 'slow',
    role: 'Support slow',
    statLine: 'Control and stall',
    effects: ['slow'],
    canTargetGround: true,
    canTargetFlying: true,
    slowFactor: 0.5,
    slowDuration: 2,
  },
  laserPointer: {
    id: 'laserPointer',
    name: 'Laser Pointer',
    cost: 150,
    range: 20,
    damage: 8,
    fireRate: 4,
    projectileSpeed: 60,
    color: '#ff0000',
    role: 'Precision beam',
    statLine: 'Shield breaker',
    effects: ['antiAir'],
    canTargetGround: true,
    canTargetFlying: true,
    bonusVsShielded: 1.75,
  },
  catnipBomb: {
    id: 'catnipBomb',
    name: 'Catnip Bomb',
    cost: 200,
    range: 6,
    damage: 15,
    fireRate: 0.5,
    projectileSpeed: 15,
    color: '#4ade80',
    special: 'aoe',
    role: 'Area damage',
    statLine: 'Crowd control',
    effects: ['splash'],
    canTargetGround: true,
    canTargetFlying: false,
    splashRadius: 4,
    splashFalloff: 0.5,
  },
  treatDispenser: {
    id: 'treatDispenser',
    name: 'Treat Dispenser',
    cost: 90,
    range: 9,
    damage: 4,
    fireRate: 6,
    projectileSpeed: 32,
    color: '#d8973c',
    role: 'Anti-swarm',
    statLine: 'Rapid-fire lane hold',
    effects: [],
    canTargetGround: true,
    canTargetFlying: false,
  },
  birdWhistle: {
    id: 'birdWhistle',
    name: 'Bird Whistle',
    cost: 135,
    range: 15,
    damage: 14,
    fireRate: 2.5,
    projectileSpeed: 50,
    color: '#2cb9b0',
    role: 'Flying hunter',
    statLine: 'Anti-air shield check',
    effects: ['antiAir'],
    canTargetGround: false,
    canTargetFlying: true,
    bonusVsFlying: 2,
    bonusVsShielded: 1.5,
  },
  tunaMortar: {
    id: 'tunaMortar',
    name: 'Tuna Mortar',
    cost: 240,
    range: 18,
    damage: 22,
    fireRate: 0.7,
    projectileSpeed: 18,
    color: '#6e8aa5',
    role: 'Anti-armor splash',
    statLine: 'Siege against tanks',
    effects: ['splash', 'armorPierce'],
    canTargetGround: true,
    canTargetFlying: false,
    splashRadius: 5,
    splashFalloff: 0.5,
    armorPierce: 6,
  },
  magnetCollar: {
    id: 'magnetCollar',
    name: 'Magnet Collar',
    cost: 280,
    range: 13,
    damage: 10,
    fireRate: 1.2,
    projectileSpeed: 40,
    color: '#40d9ff',
    role: 'Chain control',
    statLine: 'Slow and arc damage',
    effects: ['chain', 'slow'],
    canTargetGround: true,
    canTargetFlying: true,
    slowFactor: 0.7,
    slowDuration: 1.25,
    chainCount: 4,
    chainRange: 4.5,
    chainFalloff: 0.75,
  },
};
